Enhavo\Bundle\ArticleBundle\Entity\Article:
    type: entity
    table: article_article
    repositoryClass: Enhavo\Bundle\ArticleBundle\Repository\ArticleRepository

    fields:
        teaser:
            type: text
            nullable: true

    oneToOne:
        picture:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\MediaBundle\Model\FileInterface
            orphanRemoval: true

        content:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\BlockBundle\Model\NodeInterface

    manyToMany:
        categories:
            cascade: ['persist', 'refresh']
            targetEntity: Enhavo\Bundle\TaxonomyBundle\Model\TermInterface
            joinTable:
                name: article_article_category
                joinColumns:
                  article_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                inverseJoinColumns:
                  category_id:
                    referencedColumnName: id
                    onDelete: CASCADE

        tags:
            cascade: ['persist', 'refresh']
            targetEntity: Enhavo\Bundle\TaxonomyBundle\Model\TermInterface
            joinTable:
                name: article_article_tag
                joinColumns:
                    article_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
                        onDelete: CASCADE
