Enhavo\Bundle\ArticleBundle\Entity\Article:
    type: entity
    table: article_article
    repositoryClass: Enhavo\Bundle\ArticleBundle\Repository\ArticleRepository

    fields:
        teaser:
            type: text
            nullable: true

    oneToOne:
        picture:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\MediaBundle\Model\FileInterface
            orphanRemoval: true

        grid:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\GridBundle\Model\GridInterface

    manyToMany:
        categories:
            cascade: ['persist', 'refresh']
            targetEntity: Enhavo\Bundle\CategoryBundle\Model\CategoryInterface
            joinTable:
                name: article_category
                joinColumns:
                  article_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                inverseJoinColumns:
                  category_id:
                    referencedColumnName: id
                    onDelete: CASCADE