Enhavo\Bundle\ArticleBundle\Entity\Article:
    type: mappedSuperclass
    table: article_article
    repositoryClass: Enhavo\Bundle\ArticleBundle\Repository\ArticleRepository

    fields:
        teaser:
            type: text
            nullable: true

    manyToOne:
        picture:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\MediaBundle\Entity\File

    oneToOne:
        grid:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\GridBundle\Entity\Grid
