Enhavo\Bundle\ArticleBundle\Entity\ArticleListBlock:
    type: entity
    table: article_article_list_block

    fields:
        limit:
            type: integer
            nullable: true
            column: '`limit`'
        pagination:
            type: boolean
            nullable: true

    lifecycleCallbacks: {  }
