Enhavo\Bundle\ArticleBundle\Entity\Article:
    type: mappedSuperclass
    table: article_article
    repositoryClass: Enhavo\Bundle\ArticleBundle\Repository\ArticleRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 255
            nullable: true

        teaser:
            type: text
            nullable: true

        slug:
            type: string
            length: 255
            nullable: true
            gedmo:
                slug:
                    separator: -
                    style: default
                    updatable: false
                    fields: ['title']

        meta_description:
            type: text
            nullable: true

        page_title:
            type: text
            nullable: true

        publication_date:
            type: datetime
            nullable: true

        priority:
            type: float
            nullable: true

        change_frequency:
            type: string
            length: 255
            nullable: true

        public:
            type: boolean
            nullable: true

        created:
            type: datetime
            nullable: true

        updated:
            type: datetime
            nullable: true

        social_media:
            type: boolean
            nullable: true

    manyToOne:
        route:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\AppBundle\Entity\Route

    oneToOne:
        content:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\GridBundle\Entity\Content
        workflow_status:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\WorkflowBundle\Entity\WorkflowStatus

    manyToMany:
        picture:
            cascade: ['persist', 'refresh', 'remove']
            targetEntity: Enhavo\Bundle\MediaBundle\Entity\File
            joinTable:
                name: article_article_picture
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    file_id:
                        referencedColumnName: id
            orderBy: { 'order': 'ASC' }
            
    lifecycleCallbacks:
        prePersist: [ prePersist ]
        preUpdate: [ preUpdate ]
