Enhavo\Bundle\ArticleBundle\Entity\ArticleTeaserBlock:
    type: entity
    table: article_article_teaser_block

    fields:
        layout:
            type: smallint
            nullable: true
        textLeft:
            type: boolean
            nullable: true
    manyToOne:
        article:
            targetEntity: Enhavo\Bundle\ArticleBundle\Model\ArticleInterface

    lifecycleCallbacks: {  }
