Enhavo\Bundle\ArticleBundle\Entity\Article:
    properties:
        title:
            type: text
            weight: 10
        teaser:
            type: text
            weight: 8
            type: teaser
        grid:
            type: model
