Enhavo\Bundle\ArticleBundle\Entity\Article:
    priority: 5
    index: false
    properties:
        title:
            - Plain:
                score: 10
                type: title

        text:
            - Html:
                language: true
                weight:
                  h1: 10
                default: 2
        tags:
            - Collection:
                entity: Enhavo\Bundle\ArticleBundle\Entity\Tag


Enhavo\Bundle\ArticleBundle\Entity\Tag:
    properties:
        text:
            - Plain:
                score: 5