Enhavo\Bundle\ArticleBundle\Entity\Article:
    properties:
        title:
            - Plain:
                weight: 10
                type: title

        text:
            - Html:
                type: text

        content:
            - Model
