Enhavo\Bundle\ArticleBundle\Entity\Article:
    properties:
        title:
            - Plain:
                weight: 10
                type: title
        teaser:
            - Plain:
                weight: 8
                type: teaser
        grid:
            - Model

        picture:
            - PDF:
                weight: 7
                type: pdf
