Enhavo\Bundle\ArticleBundle\Entity\Article:
    properties:
        title:
            - Plain:
                weight: 10
                type: title
        teaser:
            - Plain:
                weight: 8
                type: teaser
        text:
            - Html:
                type: text

        grid:
            - Model
