parameters:
    enhavo_article.news_resolver.class: Enhavo\Bundle\ArticleBundle\Service\ArticleResolver
    enhavo_article.news.route_content_loader.class: Enhavo\Bundle\AppBundle\Route\RouteContentLoader

services:
    enhavo_article_article:
        class: %enhavo_article.form.type.news.class%
        arguments:
            - %enhavo_article.model.news.class%
            - %enhavo_article.news_route%
            - @router
        tags:
            - { name: form.type }

    enhavo_article.news_resolver:
        class: %enhavo_article.news_resolver.class%
        arguments:
            - @service_container