parameters:
    enhavo_news.news_resolver.class: enhavo\NewsBundle\Service\NewsResolver
    enhavo_news.news.route_content_loader.class: enhavo\AdminBundle\Route\RouteContentLoader

services:
    enhavo_news_news:
        class: %enhavo_news.form.type.news.class%
        arguments:
            - %enhavo_news.model.news.class%
            - %enhavo_news.news_route%
            - @router
        tags:
            - { name: form.type }

    enhavo_news.news_resolver:
        class: %enhavo_news.news_resolver.class%
        arguments:
            - @service_container