services:
    Enhavo\Bundle\ArticleBundle\Form\Type\ArticleType:
        arguments:
            - '%enhavo_article.model.article.class%'
            - [default]
            - '%enhavo_app.translate%'
        tags:
            - { name: form.type, alias: enhavo_article_article }

    Enhavo\Bundle\ArticleBundle\Widget\ArticleCategoryWidget:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: article_category }

    enhavo_article.extend_listener.article:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\ArticleBundle\Entity\Article
            - '%enhavo_article.model.article.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Enhavo\Bundle\ArticleBundle\Menu\ArticleMenuType:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: article }

    Enhavo\Bundle\ArticleBundle\Menu\TagMenuType:
        parent: Enhavo\Bundle\AppBundle\Menu\Menu\BaseMenu
        tags:
            - { name: enhavo.menu, alias: article_tag }

    enhavo_article.statistic.article:
        class: Enhavo\Bundle\ArticleBundle\Statistic\ArticleStatistic
        calls:
          - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.statistic, alias: article }

    Enhavo\Bundle\ArticleBundle\Grid\ArticleStreamType:
        public: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.grid_item, alias: article_stream }

    Enhavo\Bundle\ArticleBundle\Widget\ArticleStreamType:
        public: true
        arguments:
            - '@enhavo_article.repository.article'
            - '@request_stack'
        tags:
            - { name: enhavo.widget, alias: article_stream }