services:
    Enhavo\Bundle\ArticleBundle\Form\Type\ArticleType:
        arguments:
            - '%enhavo_article.model.article.class%'
            - [default]
            - '%enhavo_app.translate%'
        tags:
            - { name: form.type, alias: enhavo_article_article }

    enhavo_article_article.widget.article_category:
        class: Enhavo\Bundle\ArticleBundle\Widget\ArticleCategoryWidget
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.widget, alias: article_category }

    enhavo_article.extend_listener.article:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\ArticleBundle\Entity\Article
            - '%enhavo_article.model.article.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Enhavo\Bundle\ArticleBundle\Menu\ArticleMenu:
        public: true
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: article }

    enhavo_article.statistic.article:
        class: Enhavo\Bundle\ArticleBundle\Statistic\ArticleStatistic
        calls:
          - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.statistic, alias: article }