services:
    enhavo_article_article:
        class: '%enhavo_article.form.type.article.class%'
        arguments:
            - '%enhavo_article.model.article.class%'
            - '%enhavo_article.routing.article.strategy%'
            - '%enhavo_article.routing.article.route%'
            - '%enhavo_translation.translate%'
        tags:
            - { name: form.type }

    enhavo_article_article.widget.article_category:
        class: Enhavo\Bundle\ArticleBundle\Widget\ArticleCategoryWidget
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.theme_widget, alias: article_category }

    enhavo_article.extend_listener.article:
        class: Enhavo\Bundle\AppBundle\EventListener\DoctrineExtendListener
        arguments:
            - Enhavo\Bundle\ArticleBundle\Entity\Article
            - '%enhavo_article.model.article.class%'
            - true
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    enhavo_article.menu_builder.article:
        class: Enhavo\Bundle\ArticleBundle\Menu\ArticleMenuBuilder
        calls:
          - [ 'setContainer', ['@service_container']]
        tags:
            - { name: enhavo.menu, alias: article }

    enhavo_article.statistic.article:
        class: Enhavo\Bundle\ArticleBundle\Statistic\ArticleStatistic
        calls:
          - ['setContainer', ['@service_container']]
        tags:
            - { name: enhavo.statistic, alias: article }