services:
    enhavo_article_article:
        class: %enhavo_article.form.type.article.class%
        arguments:
            - %enhavo_article.model.article.class%
            - %enhavo_article.routing.article.strategy%
            - %enhavo_article.routing.article.route%
        tags:
            - { name: form.type }