enhavo_article_article_index:
    options:
        expose: true
    path: /enhavo/article/article/index
    methods: [GET]
    defaults:
        _controller: enhavo_article.controller.article:indexAction
        _sylius:
            viewer:
                title: article.label.article
                translationDomain: EnhavoArticleBundle

enhavo_article_article_create:
    options:
        expose: true
    path: /enhavo/article/article/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_article.controller.article:createAction
        _sylius:
            viewer:
                translationDomain: EnhavoArticleBundle
                tabs:
                    main:
                        label: article.label.article
                        template: EnhavoArticleBundle:Tab:article.html.twig
                    content:
                        label: article.label.content
                        template: EnhavoArticleBundle:Tab:content.html.twig
                    seo:
                        label: article.label.seo
                        template: EnhavoArticleBundle:Tab:seo.html.twig
                actions:
                    preview:
                        type: preview
                        route: enhavo_article_article_preview
            redirect: enhavo_article_article_update

enhavo_article_article_update:
    options:
        expose: true
    path: /enhavo/article/article/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_article.controller.article:updateAction
        _sylius:
            viewer:
                translationDomain: EnhavoArticleBundle
                tabs:
                    main:
                        label: article.label.article
                        template: EnhavoArticleBundle:Tab:article.html.twig
                    content:
                        label: article.label.content
                        template: EnhavoArticleBundle:Tab:content.html.twig
                    seo:
                        label: article.label.seo
                        template: EnhavoArticleBundle:Tab:seo.html.twig
                actions:
                    preview:
                        type: preview
                        route: enhavo_article_article_preview

enhavo_article_article_table:
    options:
        expose: true
    path: /enhavo/article/article/table
    methods: [GET]
    defaults:
        _controller: enhavo_article.controller.article:tableAction
        _sylius:
            sorting:
                publicationDate: desc
            filters:
                title:
                    type: text
                    label: article.label.title
                    translation_domain: EnhavoArticleBundle
                    property: title
                public:
                    type: boolean
                    label: article.label.public
                    translation_domain: EnhavoArticleBundle
                    property: public
                    equals: true
            viewer:
                translationDomain: EnhavoArticleBundle
                columns:
                    public:
                        label: article.label.public
                        property: public
                        width: 2
                        type: boolean
                    title:
                        type: text
                        label: article.label.title
                        property: title
                        width: 7
                    publicationDate:
                        label: article.label.publicationDate
                        property: publicationDate
                        type: date
                        width: 3

enhavo_article_article_delete:
    options:
        expose: true
    path: /enhavo/article/article/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: enhavo_article.controller.article:deleteAction

enhavo_article_article_batch:
    options:
        expose: true
    path: /enhavo/article/article/batch
    methods: [POST]
    defaults:
        _controller: enhavo_article.controller.article:batchAction
        _sylius:
            paginate: false
            criteria:
                id: $ids
            batches:
                delete:
                    type: delete
                publish:
                    type: publish

enhavo_article_article_preview:
    options:
        expose: true
    path: /enhavo/article/article/preview
    methods: [GET]
    defaults:
        _controller: enhavo_article.controller.article:previewAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction

enhavo_article_article_resource_preview:
    options:
        expose: true
    path: /enhavo/article/article/resource/preview
    methods: [POST]
    defaults:
        _controller: enhavo_article.controller.article:previewResourceAction
        _sylius:
            viewer:
                strategy_options:
                    service: enhavo_article.controller.article:showResourceAction