enhavo_article_admin_article_index:
    path: /article/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_article_admin_api_article_index
        _endpoint:
            type: admin

enhavo_article_admin_article_create:
    path: /article/create
    defaults:
        _expose: admin
        _vue:
            component: resource-create
            groups: admin
            meta:
                api: enhavo_article_admin_api_article_create
        _endpoint:
            type: admin

enhavo_article_admin_article_update:
    path: /article/update/{id}
    defaults:
        _expose: admin
        _vue:
            component: resource-update
            groups: admin
            meta:
                api: enhavo_article_admin_api_article_update
        _endpoint:
            type: admin

enhavo_article_admin_article_delete:
    path: /article/delete
    defaults:
        _expose: admin
        _vue:
            component: resource-form
            groups: admin
        _endpoint:
            type: admin

enhavo_article_admin_article_preview:
    options:
        expose: true
    path: /enhavo/article/article/preview
    methods: [GET]
    defaults:
        _expose: admin
        _vue:
            component: resource-form
            groups: admin
        _endpoint:
            type: admin

enhavo_article_admin_article_preview_resource:
    options:
        expose: true
    path: /enhavo/article/article/preview/resource
    methods: [POST]
    defaults:
        _expose: admin
        _endpoint:
            type: preview_resource
