enhavo_article_admin_tag_index:
    path: /tag/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_article_admin_api_tag_index
        _endpoint:
            type: admin

enhavo_article_admin_tag_create:
    path: /tag/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_article_admin_api_tag_create
        _endpoint:
            type: admin

enhavo_article_admin_tag_update:
    path: /tag/update/{id}
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_article_admin_api_tag_update
        _endpoint:
            type: admin
