enhavo_content:
    sitemap:
        collectors:
            article:
                type: publish
                repository: enhavo_article.repository.article

enhavo_app:
    route:
        url_resolver:
            page:
                model: enhavo_article.article
                strategy: id
                route: enhavo_page_page_update

enhavo_theme:
    route:
        url_resolver:
            page:
                model: enhavo_article.article
                strategy: slug
                route: ~

security:
    role_hierarchy:
        ROLE_ADMIN_ENHAVO_ARTICLE_ARTICLE_INDEX:
        ROLE_ADMIN_ENHAVO_ARTICLE_ARTICLE_UPDATE:
        ROLE_ADMIN_ENHAVO_ARTICLE_ARTICLE_CREATE:
        ROLE_ADMIN_ENHAVO_ARTICLE_ARTICLE_DELETE: