enhavo_content:
    sitemap:
        collectors:
            article:
                type: publish
                repository: enhavo_article.repository.article

enhavo_app:
    route:
        url_resolver:
            page:
                model: enhavo_article.article
                strategy: id
                route: enhavo_page_page_update
    roles:
        enhavo_article_article_index:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_INDEX
            label: article.role.label.index
            translationDomain: EnhavoArticleBundle
        enhavo_article_article_create:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_CREATE
            label: article.role.label.create
            translationDomain: EnhavoArticleBundle
        enhavo_article_article_update:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_UPDATE
            label: article.role.label.update
            translationDomain: EnhavoArticleBundle
        enhavo_article_article_delete:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_DELETE
            label: article.role.label.delete
            translationDomain: EnhavoArticleBundle

enhavo_theme:
    route:
        url_resolver:
            article:
                model: enhavo_article.article
                strategy: slug
                route: ~
