enhavo_content:
    sitemap:
        collectors:
            article:
                type: publish
                repository: enhavo_article.repository.article

enhavo_routing:
    classes:
        Enhavo\Bundle\ArticleBundle\Entity\Article:
            router:
                default:
                    type: slug
                    route: enhavo_article_theme_article_show
                admin:
                    type: id
                    route: enhavo_article_article_update
            generators:
                slug:
                    type: slug
                    property: title

enhavo_app:
    roles:
        enhavo_article_article_index:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_INDEX
            label: article.role.label.index
            translationDomain: EnhavoArticleBundle
        enhavo_article_article_create:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_CREATE
            label: article.role.label.create
            translationDomain: EnhavoArticleBundle
        enhavo_article_article_update:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_UPDATE
            label: article.role.label.update
            translationDomain: EnhavoArticleBundle
        enhavo_article_article_delete:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_DELETE
            label: article.role.label.delete
            translationDomain: EnhavoArticleBundle

enhavo_taxonomy:
    taxonomies:
        article_category:
            label: article.label.category
            translation_domain: EnhavoArticleBundle
