cmf_routing:
    dynamic:
        controllers_by_class:
            Enhavo\Bundle\ArticleBundle\Entity\Article: enhavo_article.controller.article::showResourceAction

enhavo_content:
    sitemap:
        collectors:
            article:
                type: publish
                repository: enhavo_article.repository.article

enhavo_routing:
    classes:
        Enhavo\Bundle\ArticleBundle\Entity\Article:
            router:
                default:
                    type: template
                    template: article
                view:
                    type: id
                    route: enhavo_article_article_update
                admin:
                    type: admin
                    index_route: enhavo_article_article_index
                    update_route: enhavo_article_article_update
            generators:
                slug:
                    type: slug
                    property: title

enhavo_app:
    template_paths:
        enhavo_article:
            path: '@EnhavoArticleBundle/Resources/views'
            alias: EnhavoArticle
            priority: 10
    roles:
        enhavo_article_article_index:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_INDEX
            label: article.role.label.index
            translation_domain: EnhavoArticleBundle
        enhavo_article_article_create:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_CREATE
            label: article.role.label.create
            translation_domain: EnhavoArticleBundle
        enhavo_article_article_update:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_UPDATE
            label: article.role.label.update
            translation_domain: EnhavoArticleBundle
        enhavo_article_article_delete:
            role: ROLE_ENHAVO_ARTICLE_ARTICLE_DELETE
            label: article.role.label.delete
            translation_domain: EnhavoArticleBundle

enhavo_taxonomy:
    taxonomies:
        article_category:
            label: article.label.category
            translation_domain: EnhavoArticleBundle
        article_tag:
            label: article.label.tag
            translation_domain: EnhavoArticleBundle

enhavo_template:
    template:
        article:
            repository: enhavo_article.repository.article
            label: article.label.article
            translation_domain: EnhavoArticleBundle
            resource_template: theme/resource/article/resource.html.twig

doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\ArticleBundle\Model\ArticleInterface: Enhavo\Bundle\ArticleBundle\Entity\Article

enhavo_resource:
    resources:
        enhavo_article.article:
            classes:
                model: Enhavo\Bundle\ArticleBundle\Entity\Article
    grids:
        enhavo_article.article:
            extends: enhavo_resource.grid
            resource: enhavo_article.article
            filters:
                title:
                    type: text
                    property: title
                    label: Text
                public:
                    type: boolean
                    label: article.label.public
                    translation_domain: EnhavoArticleBundle
                    property: public
                    equals: true
                category:
                    type: taxonomy
                    label: article.label.category
                    translation_domain: EnhavoArticleBundle
                    taxonomy: article_category
                    property: categories
            columns:
                public:
                    label: article.label.public
                    translation_domain: EnhavoArticleBundle
                    property: public
                    width: 2
                    type: boolean
                    sortable: true
                    condition: "desktop"
                title:
                    type: text
                    label: article.label.title
                    translation_domain: EnhavoArticleBundle
                    property: title
                    width: 7
                    sortable: true
                publicationDate:
                    label: article.label.publicationDate
                    translation_domain: EnhavoArticleBundle
                    property: publicationDate
                    type: date
                    width: 3
                    sortable: true
                    condition: "desktop || tablet"
            batches:
                delete:
                    type: delete
                publish:
                    type: publish

    inputs:
        enhavo_article.article:
            extends: enhavo_resource.input
            resource: enhavo_article.article
            form: Enhavo\Bundle\ArticleBundle\Form\Type\ArticleType
            form_options:
                component_theme: admin
            tabs:
                main:
                    type: form
                    label: article.label.article
                    translation_domain: EnhavoArticleBundle
                    arrangement: |
                        teaser
                        link
                        title
                        picture
                        categories
                        tags
                        publication_date
                        published_until
                        public
                content:
                    type: content
                meta:
                    type: meta
            actions:
                duplicate:
                    type: duplicate
                    route: enhavo_article_admin_api_duplicate
                    permission: ROLE_ENHAVO_ARTICLE_ARTICLE_CREATE
                    enabled: 'expr:resource && resource.getId()'
                preview:
                    type: preview
                    route: enhavo_article_admin_article_preview
                    api_route: enhavo_article_admin_api_preview
                    enabled: 'expr:resource && resource.getId()'
                comments:
                    type: comments
                    enabled: 'expr:resource && resource.getId()'
#                auto_save:
#                    type: auto_save
