enhavo_translation:
    metadata:
        Enhavo\Bundle\ArticleBundle\Entity\Article:
            properties:
                title:
                    type: text
                    form_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                teaser:
                    type: text
                    form_type: 'Enhavo\Bundle\FormBundle\Form\Type\WysiwygType'