enhavo_translation:
    metadata:
        Enhavo\Bundle\ArticleBundle\Entity\Article:
            properties:
                title:
                    type: text
                teaser:
                    type: text