enhavo_article_theme_category:
    options:
        expose: true
    path: /article/category/{slug}
    methods: [GET]
    defaults:
        _controller: enhavo_article.controller.article:categoryAction
        _sylius:

enhavo_article_theme_article_show:
    options:
        expose: true
    path: /article/show/{slug}
    methods: [GET]
    defaults:
        _controller: enhavo_article.controller.article:categoryAction
        _sylius: