enhavo_article_article_index:
    options:
        expose: true
    path: /enhavo/article/article/index
    methods: [GET]
    defaults:
        _controller: enhavo_article.controller.article:indexAction
        _sylius:
            template: EnhavoAppBundle:Resource:index.html.twig
        _viewer:

enhavo_article_article_create:
    options:
        expose: true
    path: /enhavo/article/article/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_article.controller.article:createAction
        _sylius:
            template: EnhavoAppBundle:Resource:create.html.twig
        _viewer:
            translationDomain: EnhavoArticleBundle
            tabs:
                article:
                    label: article.label.article
                    template: EnhavoArticleBundle:Tab:article.html.twig
                content:
                    label: article.label.content
                    template: EnhavoArticleBundle:Tab:content.html.twig
                seo:
                    label: article.label.seo
                    template: EnhavoArticleBundle:Tab:seo.html.twig
            buttons:
                preview:
                    route: enhavo_article_article_preview
                    label: label.preview
                    icon: icon-eye

enhavo_article_article_update:
    options:
        expose: true
    path: /enhavo/article/article/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_article.controller.article:updateAction
        _sylius:
            template: EnhavoAppBundle:Resource:update.html.twig
        _viewer:
            translationDomain: EnhavoArticleBundle
            tabs:
                article:
                    label: article.label.article
                    template: EnhavoArticleBundle:Tab:article.html.twig
                content:
                    label: article.label.content
                    template: EnhavoArticleBundle:Tab:content.html.twig
                seo:
                    label: article.label.seo
                    template: EnhavoArticleBundle:Tab:seo.html.twig
            buttons:
                preview:
                    route: enhavo_article_article_preview
                    label: label.preview
                    icon: icon-eye

enhavo_article_article_table:
    options:
        expose: true
    path: /enhavo/article/article/table/{page}
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_article.controller.article:tableAction
        _sylius:
            template: EnhavoAppBundle:Resource:table.html.twig
        _viewer:
            translationDomain: EnhavoArticleBundle
            table:
                columns:
                    id:
                        label: article.label.id
                        property: id
                        width: 1
                    title:
                        label: article.label.title
                        property: title
                        width: 11

enhavo_article_article_delete:
    options:
        expose: true
    path: /enhavo/article/article/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: enhavo_article.controller.article:deleteAction

enhavo_article_article_batch:
    options:
        expose: true
    path: /enhavo/article/article/batch
    methods: [POST]
    defaults:
        _controller: enhavo_article.controller.article:batchAction

enhavo_article_article_preview:
    options:
        expose: true
    path: /enhavo/article/article/preview
    methods: [POST]
    defaults:
        _controller: enhavo_article.controller.article:previewAction
        _viewer:
            service: enhavo_article.controller.article:showResource