enhavo_article_article_index:
    options:
        expose: true
    path: /admin/enhavo/news/news/index
    methods: [GET]
    defaults:
        _controller: enhavo_article.controller.news:indexAction
        _sylius:
            template: EnhavoAppBundle:Resource:index.html.twig
        _viewer:

enhavo_article_article_create:
    options:
        expose: true
    path: /admin/enhavo/news/news/create
    methods: [GET,POST]
    defaults:
        _controller: enhavo_article.controller.news:createAction
        _sylius:
            template: EnhavoAppBundle:Resource:create.html.twig
        _viewer:
            tabs:
                news:
                    label: Article
                    template: EnhavoArticleBundle:Tab:news.html.twig
                content:
                    label: Content
                    template: EnhavoArticleBundle:Tab:content.html.twig
                seo:
                    label: Seo
                    template: EnhavoArticleBundle:Tab:seo.html.twig
            buttons:
                preview:
                    route: enhavo_article_article_preview
                    label: label.preview
                    icon: eye

enhavo_article_article_update:
    options:
        expose: true
    path: /admin/enhavo/news/news/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_article.controller.news:updateAction
        _sylius:
            template: EnhavoAppBundle:Resource:update.html.twig
        _viewer:
            tabs:
                news:
                    label: Article
                    template: EnhavoArticleBundle:Tab:news.html.twig
                content:
                    label: Content
                    template: EnhavoArticleBundle:Tab:content.html.twig
                seo:
                    label: Seo
                    template: EnhavoArticleBundle:Tab:seo.html.twig
            buttons:
                preview:
                    route: enhavo_article_article_preview
                    label: label.preview
                    icon: eye

enhavo_article_article_table:
    options:
        expose: true
    path: /admin/enhavo/news/news/table/{page}
    methods: [GET]
    defaults:
        page: 1
        _controller: enhavo_article.controller.news:tableAction
        _sylius:
            template: EnhavoAppBundle:Resource:table.html.twig
        _viewer:
            table:
                columns:
                    id:
                        label: ID
                        property: id
                    title:
                        label: title
                        property: title

enhavo_article_article_delete:
    options:
        expose: true
    path: /admin/enhavo/news/news/delete/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_article.controller.news:deleteAction

enhavo_article_article_preview:
    options:
        expose: true
    path: /admin/enhavo/news/news/preview
    methods: [POST]
    defaults:
        _controller: enhavo_article.controller.news:previewAction
